scene:
  data_path: "data/truck/"
  output_path: "results/gsplat/truck/"
  exp_name: "exp_004"
  type: "colmap"

training_params:
  preload: True  # False:disk / True:cpu/cuda
  preload_device: "cuda:0"  # "cuda:0" / "cpu"
  preload_dtype: "fp32" # fp32 / fp16
  iterations: 30000
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001
  lambda_dssim: 0.2
  optimizer_type: "default" # "default" / sparse_adam" / "selective_adam"
  percent_dense: 0.01

  log: False
  log_interval: 100
  image_log_interval: 500
  eval: False
  eval_split_interval: 8
  eval_interval: 2000

  pose_optimize: False
  pose_updater_params:
    init: "zero"
  pose_optimizer_params:
    lr: 1e-5
    reg: 1e-6
    start_iter: 0
    end_iter: 30000

  densification_params:
    strategy: "absgrad" # "absgrad" / "mcmc"
    densification_interval: 100
    densify_from_iter: 500
    densify_until_iter: 15000
    min_opacity: 0.005
    opacity_reset_interval: 3000
    mcmc_params:
      opacity_reg: 0.01
      scale_reg: 0.01
      noise_lr: 5e5
      new_gaussian_ratio: 1.03
    absgrad_params:
      densify_grad_threshold: 0.0005

renderer_params:
  renderer_type: "gsplat"

model_params:
  image_scale: 0.25
  scene_scale: 1.0
  sh_degree: 3
  max_num_gaussians: 2_000_000
